export enum VideoCategory {
  TwoVTwo = '2v2',
  ThreeVThree = '3v3',
  FiveVFive = '5v5',
  Skirmish = 'Skirmish',
  SoloShuffle = 'Solo Shuffle',
  MythicPlus = 'Mythic+',
  Raids = 'Raids',
  Battlegrounds = 'Battlegrounds',
  Clips = 'Clips',
  Manual = 'Manual',
  FFXIVTrials = 'FFXIVTrials',
  FFXIVRaids = 'FFXIVRaids',
  FFXIVDungeons = 'FFXIVDungeons',
  FFXIVAllianceRaids = 'FFXIVAllianceRaids',
  FFXIVDeepDungeons = 'FFXIVDeepDungeons',
  FFXIVVariantDungeons = 'FFXIVVariantDungeons',
  FFXIVCriterionDungeons = 'FFXIVCriterionDungeons',
}
