// https://github.com/marzent/IINACT/blob/main/OverlayPlugin.Core/EventSources/MiniParseLoglineReader.cs#L13
// https://github.com/marzent/IINACT/blob/main/OverlayPlugin.Core/MemoryProcessors/ContentFinderSettings/LineContentFinderSettings.cs#L8
enum LogType {
  LOG_LINE = '00',
  CHANGE_ZONE = '01',
  CHANGE_PRIMARY_PLAYER = '02',
  ADD_COMBATANT = '03',
  REMOVE_COMBATANT = '04',
  ADD_BUFF = '05',
  REMOVE_BUFF = '06',
  FLYING_TEXT = '07',
  OUTGOING_ABILITY = '08',
  INCOMING_ABILITY = '10',
  PARTY_LIST = '11',
  PLAYER_STATS = '12',
  COMBATANT_HP = '13',
  STARTS_CASTING = '20',
  ABILITY = '21',
  AOE_ABILITY = '22',
  CANCEL_ABILITY = '23',
  DOT = '24',
  DEATH = '25',
  BUFF = '26',
  TARGET_ICON = '27',
  RAID_MARKER = '28',
  TARGET_MARKER = '29',
  BUFF_REMOVE = '30',
  DEBUG = '251',
  PACKET_DUMP = '252',
  VERSION = '253',
  ERROR = '254',
  TIMER = '255',
  MAP_EFFECT = '257',
  FATE_CONTROL = '258',
  CE_DIRECTOR = '259',
  IN_COMBAT = '260',
  COMBATANT = '261',
  RSV = '262',
  ACTOR_CAST_EXTRA = '263',
  ABILITY_EXTRA = '264',
  CONTENT_FINDER_SETTINGS = '265',
  NPC_YELL = '266',
  BATTLE_TALK_2 = '267',
  COUNTDOWN = '268',
  COUNTDOWN_CANCEL = '269',
  ACTOR_MOVE = '270',
  ACTOR_SET_POS = '271',
  SPAWN_NPC_EXTRA = '272',
  ACTOR_CONTROL_EXTRA = '273',
  ACTOR_CONTROL_SELF_EXTRA = '274',
}

enum Job {
  None = '00',
  GLA = '01',
  PGL = '02',
  MRD = '03',
  LNC = '04',
  ARC = '05',
  CNJ = '06',
  THM = '07',
  CRP = '08',
  BSM = '09',
  ARM = '0A',
  GSM = '0B',
  LTW = '0C',
  WVR = '0D',
  ALC = '0E',
  CUL = '0F',
  MIN = '10',
  BTN = '11',
  FSH = '12',
  PLD = '13',
  MNK = '14',
  WAR = '15',
  DRG = '16',
  BRD = '17',
  WHM = '18',
  BLM = '19',
  ACN = '1A',
  SMN = '1B',
  SCH = '1C',
  ROG = '1D',
  NIN = '1E',
  MCH = '1F',
  DRK = '20',
  AST = '21',
  SAM = '22',
  RDM = '23',
  BLU = '24',
  GNB = '25',
  DNC = '26',
  RPR = '27',
  SGE = '28',
  VPR = '29',
  PCT = '2A',
}

enum Difficulty {
  'Normal',
  'Hard',
  'Extreme',
  'Savage',
  'Chaotic',
  'Ultimate',
  'Unreal',
  'Quantum',
}

enum Expansion {
  'A Realm Reborn',
  'Heavensward',
  'Stormblood',
  'Shadowbringers',
  'Endwalker',
  'Dawntrail',
}

enum ContentType {
  'Dungeon',
  'Trial',
  'Raid',
  'Alliance Raid',
  'Guildhest',
  'Field Operation',
  'Treasure Dungeon',
  'Deep Dungeon',
  'Variant Dungeon',
  'Criterion Dungeon',
  'PVP',
}

type Zone = {
  id: number;
  rawName: string;
  name: string;
  type: ContentType;
  expansion: Expansion;
  difficulty?: Difficulty;
};

export { LogType, Job, Difficulty, Expansion, ContentType, Zone };
