import { ContentType, Difficulty, Expansion, Zone } from './FFXIVTypes';

// taken from TerritoryType
const zones: Zone[] = [
  {
    id: 142,
    name: "the Dragon's Neck",
    type: ContentType.Trial,
    expansion: Expansion['A Realm Reborn'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 151,
    name: 'the World of Darkness',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 159,
    name: "the Wanderer's Palace",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 160,
    name: 'Pharos Sirius',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 167,
    name: 'Amdapor Keep',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 171,
    name: 'Dzemael Darkhold',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 172,
    name: 'the Aurum Vale',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 174,
    name: 'the Labyrinth of the Ancients',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 188,
    name: "the Wanderer's Palace (Hard)",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 189,
    name: 'Amdapor Keep (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 190,
    name: 'Under the Armor',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 191,
    name: 'Pulling Poison Posies',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 192,
    name: 'Stinging Back',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 193,
    name: 'the Final Coil of Bahamut - Turn 1',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 194,
    name: 'the Final Coil of Bahamut - Turn 2',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 195,
    name: 'the Final Coil of Bahamut - Turn 3',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 196,
    name: 'the Final Coil of Bahamut - Turn 4',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 214,
    name: 'Basic Training: Enemy Parties',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 215,
    name: 'Basic Training: Enemy Strongholds',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 216,
    name: 'Hero on the Half Shell',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 219,
    name: 'Flicking Sticks and Taking Names',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 220,
    name: "All's Well that Ends in the Well",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 221,
    name: 'More than a Feeler',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 222,
    name: 'Annoy the Void',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 223,
    name: 'Shadow and Claw',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 241,
    name: 'the Binding Coil of Bahamut - Turn 1',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 242,
    name: 'the Binding Coil of Bahamut - Turn 2',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 243,
    name: 'the Binding Coil of Bahamut - Turn 3',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 244,
    name: 'the Binding Coil of Bahamut - Turn 4',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 245,
    name: 'the Binding Coil of Bahamut - Turn 5',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 281,
    name: 'the <Emphasis>Whorleater</Emphasis> (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 292,
    name: 'the Bowl of Embers (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 293,
    name: 'the Navel (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 294,
    name: 'the Howling Eye (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 295,
    name: 'the Bowl of Embers (Extreme)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 296,
    name: 'the Navel (Extreme)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 297,
    name: 'the Howling Eye (Extreme)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 298,
    name: 'Long Live the Queen',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 299,
    name: 'Ward Up',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 300,
    name: 'Solemn Trinity',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 348,
    name: "the Minstrel's Ballad: Ultima's Bane",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 349,
    name: 'Copperbell Mines (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 350,
    name: 'Haukke Manor (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 353,
    name: 'Special Event I',
    expansion: Expansion.Stormblood,
  },
  {
    id: 354,
    name: 'Special Event II',
    expansion: Expansion.Shadowbringers,
  },
  {
    id: 355,
    name: 'the Second Coil of Bahamut - Turn 1',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 356,
    name: 'the Second Coil of Bahamut - Turn 2',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 357,
    name: 'the Second Coil of Bahamut - Turn 3',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 358,
    name: 'the Second Coil of Bahamut - Turn 4',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 359,
    name: 'the <Emphasis>Whorleater</Emphasis> (Extreme)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 360,
    name: 'Halatali (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 361,
    name: 'Hullbreaker Isle',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 362,
    name: "Brayflox's Longstop (Hard)",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 363,
    name: 'the Lost City of Amdapor',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 364,
    name: 'Thornmarch (Extreme)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 365,
    name: 'the Stone Vigil (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 366,
    name: 'Battle on the Big Bridge',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 367,
    name: 'the Sunken Temple of Qarn (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 368,
    name: 'A Relic Reborn: the Chimera',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 369,
    name: 'A Relic Reborn: the Hydra',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 372,
    name: 'Syrcus Tower',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 373,
    name: 'the Tam–Tara Deepcroft (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 374,
    name: 'the Striking Tree (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 375,
    name: 'the Striking Tree (Extreme)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 376,
    name: 'the Borderland Ruins (Secure)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 377,
    name: 'the Akh Afah Amphitheatre (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 378,
    name: 'the Akh Afah Amphitheatre (Extreme)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 380,
    name: 'the Second Coil of Bahamut (Savage) - Turn 1',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 381,
    name: 'the Second Coil of Bahamut (Savage) - Turn 2',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 382,
    name: 'the Second Coil of Bahamut (Savage) - Turn 3',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 383,
    name: 'the Second Coil of Bahamut (Savage) - Turn 4',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 387,
    name: 'Sastasha (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 394,
    name: "Urth's Fount",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 396,
    name: 'Battle in the Big Keep',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 420,
    name: 'Neverreap',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 426,
    name: 'the Chrysalis',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 430,
    name: 'the Fractal Continuum',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 431,
    name: 'Seal Rock (Seize)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 432,
    name: 'Thok ast Thok (Hard)',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 434,
    name: 'the Dusk Vigil',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 436,
    name: 'the Limitless Blue (Hard)',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 437,
    name: 'the Singularity Reactor',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 442,
    name: 'Alexander - The Fist of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 443,
    name: 'Alexander - The Cuff of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 444,
    name: 'Alexander - The Arm of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 445,
    name: 'Alexander - The Burden of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 446,
    name: 'Thok ast Thok (Extreme)',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 447,
    name: 'the Limitless Blue (Extreme)',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 448,
    name: "the Minstrel's Ballad: Thordan's Reign",
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 449,
    name: 'Alexander - The Fist of the Father (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 450,
    name: 'Alexander - The Cuff of the Father (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 451,
    name: 'Alexander - The Arm of the Father (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 452,
    name: 'Alexander - The Burden of the Father (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 508,
    name: 'the Void Ark',
    expansion: Expansion.Heavensward,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 509,
    name: 'the Gilded Araya',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 510,
    name: 'Pharos Sirius (Hard)',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 511,
    name: "Saint Mocianne's Arboretum",
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 517,
    name: 'Containment Bay S1T7',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 519,
    name: 'the Lost City of Amdapor (Hard)',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 520,
    name: 'Alexander - The Fist of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 521,
    name: 'Alexander - The Cuff of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 522,
    name: 'Alexander - The Arm of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 523,
    name: 'Alexander - The Burden of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 524,
    name: 'Containment Bay S1T7 (Extreme)',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 529,
    name: 'Alexander - The Fist of the Son (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 530,
    name: 'Alexander - The Cuff of the Son (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 531,
    name: 'Alexander - The Arm of the Son (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 532,
    name: 'Alexander - The Burden of the Son (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 554,
    name: 'the Fields of Glory (Shatter)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 556,
    name: 'the Weeping City of Mhach',
    expansion: Expansion.Heavensward,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 557,
    name: 'Hullbreaker Isle (Hard)',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 558,
    name: 'the Aquapolis',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 559,
    name: 'the Final Steps of Faith',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 561,
    name: 'the Palace of the Dead (Floors 1-10)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 562,
    name: 'the Palace of the Dead (Floors 11-20)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 563,
    name: 'the Palace of the Dead (Floors 21-30)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 564,
    name: 'the Palace of the Dead (Floors 31-40)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 565,
    name: 'the Palace of the Dead (Floors 41-50)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 566,
    name: "the Minstrel's Ballad: Nidhogg's Rage",
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 576,
    name: 'Containment Bay P1T6',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 577,
    name: 'Containment Bay P1T6 (Extreme)',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 578,
    name: 'the Great Gubal Library (Hard)',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 580,
    name: 'Alexander - The Eyes of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 581,
    name: 'Alexander - The Breath of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 582,
    name: 'Alexander - The Heart of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 583,
    name: 'Alexander - The Soul of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 584,
    name: 'Alexander - The Eyes of the Creator (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 585,
    name: 'Alexander - The Breath of the Creator (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 586,
    name: 'Alexander - The Heart of the Creator (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 587,
    name: 'Alexander - The Soul of the Creator (Savage)',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 593,
    name: 'the Palace of the Dead (Floors 51-60)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 594,
    name: 'the Palace of the Dead (Floors 61-70)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 595,
    name: 'the Palace of the Dead (Floors 71-80)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 596,
    name: 'the Palace of the Dead (Floors 81-90)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 597,
    name: 'the Palace of the Dead (Floors 91-100)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 598,
    name: 'the Palace of the Dead (Floors 101-110)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 599,
    name: 'the Palace of the Dead (Floors 111-120)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 600,
    name: 'the Palace of the Dead (Floors 121-130)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 601,
    name: 'the Palace of the Dead (Floors 131-140)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 602,
    name: 'the Palace of the Dead (Floors 141-150)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 603,
    name: 'the Palace of the Dead (Floors 151-160)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 604,
    name: 'the Palace of the Dead (Floors 161-170)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 605,
    name: 'the Palace of the Dead (Floors 171-180)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 606,
    name: 'the Palace of the Dead (Floors 181-190)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 607,
    name: 'the Palace of the Dead (Floors 191-200)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 616,
    name: 'Shisui of the Violet Tides',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 617,
    name: 'Sohm Al (Hard)',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 627,
    name: 'Dun Scaith',
    expansion: Expansion.Heavensward,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 637,
    name: 'Containment Bay Z1T9',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 638,
    name: 'Containment Bay Z1T9 (Extreme)',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 662,
    name: 'Kugane Castle',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 663,
    name: 'the Temple of the Fist',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 674,
    name: 'the Pool of Tribute',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 677,
    name: 'the Pool of Tribute (Extreme)',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 679,
    name: 'the Royal Menagerie',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 691,
    name: 'Deltascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 692,
    name: 'Deltascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 693,
    name: 'Deltascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 694,
    name: 'Deltascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 695,
    name: 'Deltascape V1.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 696,
    name: 'Deltascape V2.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 697,
    name: 'Deltascape V3.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 698,
    name: 'Deltascape V4.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 712,
    name: 'the Lost Canals of Uznair',
    expansion: Expansion.Stormblood,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 719,
    name: 'Emanation',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 720,
    name: 'Emanation (Extreme)',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 725,
    name: 'the Hidden Canals of Uznair',
    expansion: Expansion.Stormblood,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 729,
    name: 'Astragalos',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 730,
    name: "the Minstrel's Ballad: Shinryu's Domain",
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 732,
    name: 'the Forbidden Land, Eureka Anemos',
    expansion: Expansion.Stormblood,
    type: ContentType['Field Operation'],
  },
  {
    id: 733,
    name: 'the Unending Coil of Bahamut (Ultimate)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 734,
    name: 'the Royal City of Rabanastre',
    expansion: Expansion.Stormblood,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 742,
    name: "Hells' Lid",
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 743,
    name: 'the Fractal Continuum (Hard)',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 746,
    name: 'the Jade Stoa',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 748,
    name: 'Sigmascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 749,
    name: 'Sigmascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 750,
    name: 'Sigmascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 751,
    name: 'Sigmascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 752,
    name: 'Sigmascape V1.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 753,
    name: 'Sigmascape V2.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 754,
    name: 'Sigmascape V3.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 755,
    name: 'Sigmascape V4.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 758,
    name: 'the Jade Stoa (Extreme)',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 761,
    name: 'the Great Hunt',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 762,
    name: 'the Great Hunt (Extreme)',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 763,
    name: 'the Forbidden Land, Eureka Pagos',
    expansion: Expansion.Stormblood,
    type: ContentType['Field Operation'],
  },
  {
    id: 768,
    name: "the Swallow's Compass",
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 776,
    name: 'the Ridorana Lighthouse',
    expansion: Expansion.Stormblood,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 777,
    name: "the Weapon's Refrain (Ultimate)",
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 778,
    name: 'Castrum Fluminis',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 779,
    name: "the Minstrel's Ballad: Tsukuyomi's Pain",
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 788,
    name: "Saint Mocianne's Arboretum (Hard)",
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 791,
    name: 'Hidden Gorge',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 794,
    name: 'the Shifting Altars of Uznair',
    expansion: Expansion.Stormblood,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 795,
    name: 'the Forbidden Land, Eureka Pyros',
    expansion: Expansion.Stormblood,
    type: ContentType['Field Operation'],
  },
  {
    id: 798,
    name: 'Alphascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 799,
    name: 'Alphascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 800,
    name: 'Alphascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 801,
    name: 'Alphascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 802,
    name: 'Alphascape V1.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 803,
    name: 'Alphascape V2.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 804,
    name: 'Alphascape V3.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 805,
    name: 'Alphascape V4.0 (Savage)',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 806,
    name: 'Kugane Ohashi',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 810,
    name: "Hells' Kier",
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 811,
    name: "Hells' Kier (Extreme)",
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 821,
    name: 'Dohn Mheg',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 822,
    name: 'Mt. Gulg',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 823,
    name: 'the Qitana Ravel',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 824,
    name: 'the Wreath of Snakes',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 825,
    name: 'the Wreath of Snakes (Extreme)',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 826,
    name: 'the Orbonne Monastery',
    expansion: Expansion.Stormblood,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 827,
    name: 'the Forbidden Land, Eureka Hydatos',
    expansion: Expansion.Stormblood,
    type: ContentType['Field Operation'],
  },
  {
    id: 836,
    name: "Malikah's Well",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 837,
    name: 'Holminster Switch',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 838,
    name: 'Amaurot',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 840,
    name: 'the Twinning',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 841,
    name: 'Akadaemia Anyder',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 845,
    name: 'the Dancing Plague',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 846,
    name: 'the Crown of the Immaculate',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 847,
    name: 'the Dying Gasp',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 848,
    name: 'the Crown of the Immaculate (Extreme)',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 849,
    name: "Eden's Gate: Resurrection",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 850,
    name: "Eden's Gate: Descent",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 851,
    name: "Eden's Gate: Inundation",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 852,
    name: "Eden's Gate: Sepulture",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 853,
    name: "Eden's Gate: Resurrection (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 854,
    name: "Eden's Gate: Descent (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 855,
    name: "Eden's Gate: Inundation (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 856,
    name: "Eden's Gate: Sepulture (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 858,
    name: 'the Dancing Plague (Extreme)',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 879,
    name: 'The Dungeons of Lyhe Ghiah',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 882,
    name: 'the Copied Factory',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 884,
    name: 'the Grand Cosmos',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 885,
    name: "the Minstrel's Ballad: Hades's Elegy",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 887,
    name: 'the Epic of Alexander (Ultimate)',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 888,
    name: 'Onsal Hakair (Danshig Naadam)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 897,
    name: 'Cinder Drift',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 898,
    name: 'Anamnesis Anyder',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 902,
    name: "Eden's Verse: Fulmination",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 903,
    name: "Eden's Verse: Furor",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 904,
    name: "Eden's Verse: Iconoclasm",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 905,
    name: "Eden's Verse: Refulgence",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 906,
    name: "Eden's Verse: Fulmination (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 907,
    name: "Eden's Verse: Furor (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 908,
    name: "Eden's Verse: Iconoclasm (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 909,
    name: "Eden's Verse: Refulgence (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 912,
    name: 'Cinder Drift (Extreme)',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 913,
    name: 'Memoria Misera (Extreme)',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 916,
    name: "the Heroes' Gauntlet",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 917,
    name: "the Puppets' Bunker",
    expansion: Expansion.Shadowbringers,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 920,
    name: 'the Bozjan Southern Front',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Field Operation'],
  },
  {
    id: 922,
    name: 'the Seat of Sacrifice',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 923,
    name: 'the Seat of Sacrifice (Extreme)',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 924,
    name: 'the Shifting Oubliettes of Lyhe Ghiah',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 933,
    name: "Matoya's Relict",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 934,
    name: 'Castrum Marinum',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 935,
    name: 'Castrum Marinum (Extreme)',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 936,
    name: 'Delubrum Reginae',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Field Operation'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 937,
    name: 'Delubrum Reginae (Savage)',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Field Operation'],
    difficulty: Difficulty.Savage,
  },
  {
    id: 938,
    name: "Paglth'an",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 942,
    name: "Eden's Promise: Umbra",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 943,
    name: "Eden's Promise: Litany",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 944,
    name: "Eden's Promise: Anamorphosis",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 945,
    name: "Eden's Promise: Eternity",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 946,
    name: "Eden's Promise: Umbra (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 947,
    name: "Eden's Promise: Litany (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 948,
    name: "Eden's Promise: Anamorphosis (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 949,
    name: "Eden's Promise: Eternity (Savage)",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 950,
    name: 'the Cloud Deck',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 951,
    name: 'the Cloud Deck (Extreme)',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 952,
    name: 'the Tower of Zot',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 966,
    name: "the Tower at Paradigm's Breach",
    expansion: Expansion.Shadowbringers,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 968,
    name: "Dragonsong's Reprise (Ultimate)",
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 969,
    name: 'the Tower of Babil',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 970,
    name: 'Vanaspati',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 973,
    name: 'the Dead Ends',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 974,
    name: 'Ktisis Hyperboreia',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 975,
    name: 'Zadnor',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Field Operation'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 976,
    name: 'Smileton',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 978,
    name: 'the Aitiascope',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 986,
    name: 'the Stigma Dreamscape',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 992,
    name: 'the Dark Inside',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 993,
    name: "the Minstrel's Ballad: Zodiark's Fall",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 995,
    name: 'the Mothercrystal',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 996,
    name: "the Minstrel's Ballad: Hydaelyn's Call",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 997,
    name: 'the Final Day',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 998,
    name: "the Minstrel's Ballad: Endsinger's Aria",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1000,
    name: 'the Excitatron 6000',
    expansion: Expansion.Endwalker,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 1002,
    name: 'Asphodelos: The First Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1003,
    name: 'Asphodelos: The First Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1004,
    name: 'Asphodelos: The Second Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1005,
    name: 'Asphodelos: The Second Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1006,
    name: 'Asphodelos: The Third Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1007,
    name: 'Asphodelos: The Third Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1008,
    name: 'Asphodelos: The Fourth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1009,
    name: 'Asphodelos: The Fourth Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1036,
    name: 'Sastasha',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1037,
    name: 'the Tam–Tara Deepcroft',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1038,
    name: 'Copperbell Mines',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1039,
    name: 'the Thousand Maws of Toto–Rak',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1040,
    name: 'Haukke Manor',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1041,
    name: "Brayflox's Longstop",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1042,
    name: 'the Stone Vigil',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1043,
    name: 'Castrum Meridianum',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1044,
    name: 'the Praetorium',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1045,
    name: 'the Bowl of Embers',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1046,
    name: 'the Navel',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1047,
    name: 'the Howling Eye',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1048,
    name: 'the Porta Decumana',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1050,
    name: "Alzadaal's Legacy",
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1054,
    name: 'Aglaia',
    expansion: Expansion.Endwalker,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1062,
    name: 'Snowcloak',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1063,
    name: 'the Keeper of the Lake',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1064,
    name: 'Sohm Al',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1065,
    name: 'the Aery',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1066,
    name: 'the Vault',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1067,
    name: 'Thornmarch (Hard)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 1069,
    name: "the Sil'dihn Subterrane",
    expansion: Expansion.Endwalker,
    type: ContentType['Variant Dungeon'],
  },
  {
    id: 1070,
    name: 'the Fell Court of Troia',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1071,
    name: "Storm's Crown",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1072,
    name: "Storm's Crown (Extreme)",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1075,
    name: "Another Sil'dihn Subterrane",
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1076,
    name: "Another Sil'dihn Subterrane (Savage)",
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Savage,
  },
  {
    id: 1081,
    name: 'Abyssos: The Fifth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1082,
    name: 'Abyssos: The Fifth Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1083,
    name: 'Abyssos: The Sixth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1084,
    name: 'Abyssos: The Sixth Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1085,
    name: 'Abyssos: The Seventh Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1086,
    name: 'Abyssos: The Seventh Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1087,
    name: 'Abyssos: The Eighth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1088,
    name: 'Abyssos: The Eighth Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1095,
    name: 'Mount Ordeals',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1096,
    name: 'Mount Ordeals (Extreme)',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1097,
    name: 'Lapis Manalis',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1099,
    name: 'Eureka Orthos (Floors 1-10)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1100,
    name: 'Eureka Orthos (Floors 11-20)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1101,
    name: 'Eureka Orthos (Floors 21-30)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1102,
    name: 'Eureka Orthos (Floors 31-40)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1103,
    name: 'Eureka Orthos (Floors 41-50)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1104,
    name: 'Eureka Orthos (Floors 51-60)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1105,
    name: 'Eureka Orthos (Floors 61-70)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1106,
    name: 'Eureka Orthos (Floors 71-80)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1107,
    name: 'Eureka Orthos (Floors 81-90)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1108,
    name: 'Eureka Orthos (Floors 91-100)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1109,
    name: 'the Great Gubal Library',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1110,
    name: 'the Aetherochemical Research Facility',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1111,
    name: 'the Antitower',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1112,
    name: 'Sohr Khai',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1113,
    name: 'Xelphatol',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1114,
    name: "Baelsar's Wall",
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1118,
    name: 'Euphrosyne',
    expansion: Expansion.Endwalker,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1122,
    name: 'the Omega Protocol (Ultimate)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 1123,
    name: 'the Shifting Gymnasion Agonon',
    expansion: Expansion.Endwalker,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 1126,
    name: 'the Aetherfont',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1136,
    name: 'the Gilded Araya',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1137,
    name: 'Mount Rokkon',
    expansion: Expansion.Endwalker,
    type: ContentType['Variant Dungeon'],
  },
  {
    id: 1140,
    name: 'the Voidcast Dais',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1141,
    name: 'the Voidcast Dais (Extreme)',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1142,
    name: 'the Sirensong Sea',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1143,
    name: "Bardam's Mettle",
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1144,
    name: 'Doma Castle',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1145,
    name: 'Castrum Abania',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1146,
    name: 'Ala Mhigo',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1147,
    name: 'Anabaseios: The Ninth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1148,
    name: 'Anabaseios: The Ninth Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1149,
    name: 'Anabaseios: The Tenth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1150,
    name: 'Anabaseios: The Tenth Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1151,
    name: 'Anabaseios: The Eleventh Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1152,
    name: 'Anabaseios: The Eleventh Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1153,
    name: 'Anabaseios: The Twelfth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1154,
    name: 'Anabaseios: The Twelfth Circle (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1155,
    name: 'Another Mount Rokkon',
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1156,
    name: 'Another Mount Rokkon (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Savage,
  },
  {
    id: 1164,
    name: 'the Lunar Subterrane',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1167,
    name: 'Ihuykatumu',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1168,
    name: 'the Abyssal Fracture',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1169,
    name: 'the Abyssal Fracture (Extreme)',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1172,
    name: 'the Drowned City of Skalla',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1173,
    name: 'the Burn',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1174,
    name: 'the Ghimlyt Dark',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1176,
    name: 'Aloalo Island',
    expansion: Expansion.Endwalker,
    type: ContentType['Variant Dungeon'],
  },
  {
    id: 1178,
    name: 'Thaleia',
    expansion: Expansion.Endwalker,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1179,
    name: 'Another Aloalo Island',
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1180,
    name: 'Another Aloalo Island (Savage)',
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Savage,
  },
  {
    id: 1193,
    name: 'Worqor Zormor',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1194,
    name: 'the Skydeep Cenote',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1195,
    name: 'Worqor Lar Dor',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1196,
    name: 'Worqor Lar Dor (Extreme)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1198,
    name: 'Vanguard',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1199,
    name: 'Alexandria',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1200,
    name: 'Everkeep',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1201,
    name: 'Everkeep (Extreme)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1202,
    name: 'the Interphos',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1203,
    name: 'Tender Valley',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1204,
    name: 'The Strayborough Deadwalk',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1208,
    name: 'Origenics',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1209,
    name: 'Cenote Ja Ja Gural',
    expansion: Expansion.Dawntrail,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 1225,
    name: 'AAC Light-heavyweight M1',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1226,
    name: 'AAC Light-heavyweight M1 (Savage)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1227,
    name: 'AAC Light-heavyweight M2',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1228,
    name: 'AAC Light-heavyweight M2 (Savage)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1229,
    name: 'AAC Light-heavyweight M3',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1230,
    name: 'AAC Light-heavyweight M3 (Savage)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1231,
    name: 'AAC Light-heavyweight M4',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1232,
    name: 'AAC Light-heavyweight M4 (Savage)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1238,
    name: 'Futures Rewritten (Ultimate)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 1241,
    name: 'The Cloud of Darkness (Chaotic)',
    expansion: Expansion.Dawntrail,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Chaotic,
  },
  {
    id: 1242,
    name: 'Yuweyawata Field Station',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1243,
    name: "the Minstrel's Ballad: Sphene's Burden",
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1245,
    name: 'Halatali',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1248,
    name: 'Jeuno: The First Walk',
    expansion: Expansion.Dawntrail,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1252,
    name: 'the Occult Crescent: South Horn',
    expansion: Expansion.Dawntrail,
    type: ContentType['Field Operation'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1256,
    name: 'AAC Cruiserweight M1',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1257,
    name: 'AAC Cruiserweight M1 (Savage)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1258,
    name: 'AAC Cruiserweight M2',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1259,
    name: 'AAC Cruiserweight M2 (Savage)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1260,
    name: 'AAC Cruiserweight M3',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1261,
    name: 'AAC Cruiserweight M3 (Savage)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1262,
    name: 'AAC Cruiserweight M4',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1263,
    name: 'AAC Cruiserweight M4 (Savage)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1266,
    name: 'the Underkeep',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1267,
    name: 'the Sunken Temple of Qarn',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1270,
    name: 'Recollection',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1271,
    name: 'Recollection (Extreme)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1273,
    name: 'the Borderland Ruins (Secure)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 1279,
    name: 'Vault Oneiron',
    expansion: Expansion.Dawntrail,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 1281,
    name: "Pilgrim's Traverse (Stones 1-10)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1282,
    name: "Pilgrim's Traverse (Stones 11-20)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1283,
    name: "Pilgrim's Traverse (Stones 21-30)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1284,
    name: "Pilgrim's Traverse (Stones 31-40)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1285,
    name: "Pilgrim's Traverse (Stones 41-50)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1286,
    name: "Pilgrim's Traverse (Stones 51-60)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1287,
    name: "Pilgrim's Traverse (Stones 61-70)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1288,
    name: "Pilgrim's Traverse (Stones 71-80)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1289,
    name: "Pilgrim's Traverse (Stones 81-90)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1290,
    name: "Pilgrim's Traverse (Stones 91-100)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1292,
    name: 'the Meso Terminal',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1295,
    name: 'the Ageless Necropolis',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1296,
    name: "the Minstrel's Ballad: Necron's Embrace",
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1300,
    name: 'the Windward Wilds',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1302,
    name: 'the Wreath of Snakes (Unreal)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Unreal,
  },
  {
    id: 1303,
    name: "Cutter's Cry",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1304,
    name: "San d'Oria: The Second Walk",
    expansion: Expansion.Dawntrail,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1306,
    name: 'the Windward Wilds (Extreme)',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1311,
    name: 'the Final Verse (Quantum)',
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Quantum,
  },
  {
    id: 1333,
    name: 'the Final Verse',
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
];

export { zones };
