import { ContentType, Difficulty, Expansion, Zone } from './FFXIVTypes';

// taken from TerritoryType
const zones: Zone[] = [
  {
    id: 142,
    rawName: "the Dragon's Neck",
    name: "The Dragon's Neck",
    type: ContentType.Trial,
    expansion: Expansion['A Realm Reborn'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 151,
    rawName: 'the World of Darkness',
    name: 'The World of Darkness',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 159,
    rawName: "the Wanderer's Palace",
    name: "The Wanderer's Palace",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 160,
    rawName: 'Pharos Sirius',
    name: 'Pharos Sirius',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 167,
    rawName: 'Amdapor Keep',
    name: 'Amdapor Keep',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 171,
    rawName: 'Dzemael Darkhold',
    name: 'Dzemael Darkhold',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 172,
    rawName: 'the Aurum Vale',
    name: 'The Aurum Vale',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 174,
    rawName: 'the Labyrinth of the Ancients',
    name: 'The Labyrinth of the Ancients',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 188,
    rawName: "the Wanderer's Palace (Hard)",
    name: "The Wanderer's Palace",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 189,
    rawName: 'Amdapor Keep (Hard)',
    name: 'Amdapor Keep',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 190,
    rawName: 'Under the Armor',
    name: 'Under the Armor',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 191,
    rawName: 'Pulling Poison Posies',
    name: 'Pulling Poison Posies',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 192,
    rawName: 'Stinging Back',
    name: 'Stinging Back',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 193,
    rawName: 'the Final Coil of Bahamut - Turn 1',
    name: 'The Final Coil of Bahamut - Turn 1',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 194,
    rawName: 'the Final Coil of Bahamut - Turn 2',
    name: 'The Final Coil of Bahamut - Turn 2',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 195,
    rawName: 'the Final Coil of Bahamut - Turn 3',
    name: 'The Final Coil of Bahamut - Turn 3',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 196,
    rawName: 'the Final Coil of Bahamut - Turn 4',
    name: 'The Final Coil of Bahamut - Turn 4',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 214,
    rawName: 'Basic Training: Enemy Parties',
    name: 'Basic Training: Enemy Parties',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 215,
    rawName: 'Basic Training: Enemy Strongholds',
    name: 'Basic Training: Enemy Strongholds',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 216,
    rawName: 'Hero on the Half Shell',
    name: 'Hero on the Half Shell',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 219,
    rawName: 'Flicking Sticks and Taking Names',
    name: 'Flicking Sticks and Taking Names',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 220,
    rawName: "All's Well that Ends in the Well",
    name: "All's Well that Ends in the Well",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 221,
    rawName: 'More than a Feeler',
    name: 'More than a Feeler',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 222,
    rawName: 'Annoy the Void',
    name: 'Annoy the Void',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 223,
    rawName: 'Shadow and Claw',
    name: 'Shadow and Claw',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 241,
    rawName: 'the Binding Coil of Bahamut - Turn 1',
    name: 'The Binding Coil of Bahamut - Turn 1',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 242,
    rawName: 'the Binding Coil of Bahamut - Turn 2',
    name: 'The Binding Coil of Bahamut - Turn 2',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 243,
    rawName: 'the Binding Coil of Bahamut - Turn 3',
    name: 'The Binding Coil of Bahamut - Turn 3',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 244,
    rawName: 'the Binding Coil of Bahamut - Turn 4',
    name: 'The Binding Coil of Bahamut - Turn 4',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 245,
    rawName: 'the Binding Coil of Bahamut - Turn 5',
    name: 'The Binding Coil of Bahamut - Turn 5',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 281,
    rawName: 'the <Emphasis>Whorleater</Emphasis> (Hard)',
    name: 'The <Emphasis>Whorleater</Emphasis>',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 292,
    rawName: 'the Bowl of Embers (Hard)',
    name: 'The Bowl of Embers',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 293,
    rawName: 'the Navel (Hard)',
    name: 'The Navel',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 294,
    rawName: 'the Howling Eye (Hard)',
    name: 'The Howling Eye',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 295,
    rawName: 'the Bowl of Embers (Extreme)',
    name: 'The Bowl of Embers',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 296,
    rawName: 'the Navel (Extreme)',
    name: 'The Navel',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 297,
    rawName: 'the Howling Eye (Extreme)',
    name: 'The Howling Eye',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 298,
    rawName: 'Long Live the Queen',
    name: 'Long Live the Queen',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 299,
    rawName: 'Ward Up',
    name: 'Ward Up',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 300,
    rawName: 'Solemn Trinity',
    name: 'Solemn Trinity',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Guildhest,
    difficulty: Difficulty.Normal,
  },
  {
    id: 348,
    rawName: "the Minstrel's Ballad: Ultima's Bane",
    name: "The Minstrel's Ballad: Ultima's Bane",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 349,
    rawName: 'Copperbell Mines (Hard)',
    name: 'Copperbell Mines',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 350,
    rawName: 'Haukke Manor (Hard)',
    name: 'Haukke Manor',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 355,
    rawName: 'the Second Coil of Bahamut - Turn 1',
    name: 'The Second Coil of Bahamut - Turn 1',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 356,
    rawName: 'the Second Coil of Bahamut - Turn 2',
    name: 'The Second Coil of Bahamut - Turn 2',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 357,
    rawName: 'the Second Coil of Bahamut - Turn 3',
    name: 'The Second Coil of Bahamut - Turn 3',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 358,
    rawName: 'the Second Coil of Bahamut - Turn 4',
    name: 'The Second Coil of Bahamut - Turn 4',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 359,
    rawName: 'the <Emphasis>Whorleater</Emphasis> (Extreme)',
    name: 'The <Emphasis>Whorleater</Emphasis>',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 360,
    rawName: 'Halatali (Hard)',
    name: 'Halatali',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 361,
    rawName: 'Hullbreaker Isle',
    name: 'Hullbreaker Isle',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 362,
    rawName: "Brayflox's Longstop (Hard)",
    name: "Brayflox's Longstop",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 363,
    rawName: 'the Lost City of Amdapor',
    name: 'The Lost City of Amdapor',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 364,
    rawName: 'Thornmarch (Extreme)',
    name: 'Thornmarch',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 365,
    rawName: 'the Stone Vigil (Hard)',
    name: 'The Stone Vigil',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 366,
    rawName: 'Battle on the Big Bridge',
    name: 'Battle on the Big Bridge',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 367,
    rawName: 'the Sunken Temple of Qarn (Hard)',
    name: 'The Sunken Temple of Qarn',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 368,
    rawName: 'A Relic Reborn: the Chimera',
    name: 'A Relic Reborn: the Chimera',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 369,
    rawName: 'A Relic Reborn: the Hydra',
    name: 'A Relic Reborn: the Hydra',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 372,
    rawName: 'Syrcus Tower',
    name: 'Syrcus Tower',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 373,
    rawName: 'the Tam–Tara Deepcroft (Hard)',
    name: 'The Tam–Tara Deepcroft',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 374,
    rawName: 'the Striking Tree (Hard)',
    name: 'The Striking Tree',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 375,
    rawName: 'the Striking Tree (Extreme)',
    name: 'The Striking Tree',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 376,
    rawName: 'the Borderland Ruins (Secure)',
    name: 'The Borderland Ruins (Secure)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 377,
    rawName: 'the Akh Afah Amphitheatre (Hard)',
    name: 'The Akh Afah Amphitheatre',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 378,
    rawName: 'the Akh Afah Amphitheatre (Extreme)',
    name: 'The Akh Afah Amphitheatre',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 380,
    rawName: 'the Second Coil of Bahamut (Savage) - Turn 1',
    name: 'The Second Coil of Bahamut (Savage) - Turn 1',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 381,
    rawName: 'the Second Coil of Bahamut (Savage) - Turn 2',
    name: 'The Second Coil of Bahamut (Savage) - Turn 2',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 382,
    rawName: 'the Second Coil of Bahamut (Savage) - Turn 3',
    name: 'The Second Coil of Bahamut (Savage) - Turn 3',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 383,
    rawName: 'the Second Coil of Bahamut (Savage) - Turn 4',
    name: 'The Second Coil of Bahamut (Savage) - Turn 4',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 387,
    rawName: 'Sastasha (Hard)',
    name: 'Sastasha',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 394,
    rawName: "Urth's Fount",
    name: "Urth's Fount",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 396,
    rawName: 'Battle in the Big Keep',
    name: 'Battle in the Big Keep',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 420,
    rawName: 'Neverreap',
    name: 'Neverreap',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 426,
    rawName: 'the Chrysalis',
    name: 'The Chrysalis',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 430,
    rawName: 'the Fractal Continuum',
    name: 'The Fractal Continuum',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 431,
    rawName: 'Seal Rock (Seize)',
    name: 'Seal Rock (Seize)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 432,
    rawName: 'Thok ast Thok (Hard)',
    name: 'Thok ast Thok',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 434,
    rawName: 'the Dusk Vigil',
    name: 'The Dusk Vigil',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 436,
    rawName: 'the Limitless Blue (Hard)',
    name: 'The Limitless Blue',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 437,
    rawName: 'the Singularity Reactor',
    name: 'The Singularity Reactor',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 442,
    rawName: 'Alexander - The Fist of the Father',
    name: 'Alexander - The Fist of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 443,
    rawName: 'Alexander - The Cuff of the Father',
    name: 'Alexander - The Cuff of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 444,
    rawName: 'Alexander - The Arm of the Father',
    name: 'Alexander - The Arm of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 445,
    rawName: 'Alexander - The Burden of the Father',
    name: 'Alexander - The Burden of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 446,
    rawName: 'Thok ast Thok (Extreme)',
    name: 'Thok ast Thok',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 447,
    rawName: 'the Limitless Blue (Extreme)',
    name: 'The Limitless Blue',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 448,
    rawName: "the Minstrel's Ballad: Thordan's Reign",
    name: "The Minstrel's Ballad: Thordan's Reign",
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 449,
    rawName: 'Alexander - The Fist of the Father (Savage)',
    name: 'Alexander - The Fist of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 450,
    rawName: 'Alexander - The Cuff of the Father (Savage)',
    name: 'Alexander - The Cuff of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 451,
    rawName: 'Alexander - The Arm of the Father (Savage)',
    name: 'Alexander - The Arm of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 452,
    rawName: 'Alexander - The Burden of the Father (Savage)',
    name: 'Alexander - The Burden of the Father',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 508,
    rawName: 'the Void Ark',
    name: 'The Void Ark',
    expansion: Expansion.Heavensward,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 509,
    rawName: 'the Gilded Araya',
    name: 'The Gilded Araya',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 510,
    rawName: 'Pharos Sirius (Hard)',
    name: 'Pharos Sirius',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 511,
    rawName: "Saint Mocianne's Arboretum",
    name: "Saint Mocianne's Arboretum",
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 517,
    rawName: 'Containment Bay S1T7',
    name: 'Containment Bay S1T7',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 519,
    rawName: 'the Lost City of Amdapor (Hard)',
    name: 'The Lost City of Amdapor',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 520,
    rawName: 'Alexander - The Fist of the Son',
    name: 'Alexander - The Fist of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 521,
    rawName: 'Alexander - The Cuff of the Son',
    name: 'Alexander - The Cuff of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 522,
    rawName: 'Alexander - The Arm of the Son',
    name: 'Alexander - The Arm of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 523,
    rawName: 'Alexander - The Burden of the Son',
    name: 'Alexander - The Burden of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 524,
    rawName: 'Containment Bay S1T7 (Extreme)',
    name: 'Containment Bay S1T7',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 529,
    rawName: 'Alexander - The Fist of the Son (Savage)',
    name: 'Alexander - The Fist of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 530,
    rawName: 'Alexander - The Cuff of the Son (Savage)',
    name: 'Alexander - The Cuff of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 531,
    rawName: 'Alexander - The Arm of the Son (Savage)',
    name: 'Alexander - The Arm of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 532,
    rawName: 'Alexander - The Burden of the Son (Savage)',
    name: 'Alexander - The Burden of the Son',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 554,
    rawName: 'the Fields of Glory (Shatter)',
    name: 'The Fields of Glory (Shatter)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 556,
    rawName: 'the Weeping City of Mhach',
    name: 'The Weeping City of Mhach',
    expansion: Expansion.Heavensward,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 557,
    rawName: 'Hullbreaker Isle (Hard)',
    name: 'Hullbreaker Isle',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 558,
    rawName: 'the Aquapolis',
    name: 'The Aquapolis',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 559,
    rawName: 'the Final Steps of Faith',
    name: 'The Final Steps of Faith',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 561,
    rawName: 'the Palace of the Dead (Floors 1-10)',
    name: 'The Palace of the Dead (Floors 1-10)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 562,
    rawName: 'the Palace of the Dead (Floors 11-20)',
    name: 'The Palace of the Dead (Floors 11-20)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 563,
    rawName: 'the Palace of the Dead (Floors 21-30)',
    name: 'The Palace of the Dead (Floors 21-30)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 564,
    rawName: 'the Palace of the Dead (Floors 31-40)',
    name: 'The Palace of the Dead (Floors 31-40)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 565,
    rawName: 'the Palace of the Dead (Floors 41-50)',
    name: 'The Palace of the Dead (Floors 41-50)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 566,
    rawName: "the Minstrel's Ballad: Nidhogg's Rage",
    name: "The Minstrel's Ballad: Nidhogg's Rage",
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 576,
    rawName: 'Containment Bay P1T6',
    name: 'Containment Bay P1T6',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 577,
    rawName: 'Containment Bay P1T6 (Extreme)',
    name: 'Containment Bay P1T6',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 578,
    rawName: 'the Great Gubal Library (Hard)',
    name: 'The Great Gubal Library',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 580,
    rawName: 'Alexander - The Eyes of the Creator',
    name: 'Alexander - The Eyes of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 581,
    rawName: 'Alexander - The Breath of the Creator',
    name: 'Alexander - The Breath of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 582,
    rawName: 'Alexander - The Heart of the Creator',
    name: 'Alexander - The Heart of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 583,
    rawName: 'Alexander - The Soul of the Creator',
    name: 'Alexander - The Soul of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 584,
    rawName: 'Alexander - The Eyes of the Creator (Savage)',
    name: 'Alexander - The Eyes of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 585,
    rawName: 'Alexander - The Breath of the Creator (Savage)',
    name: 'Alexander - The Breath of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 586,
    rawName: 'Alexander - The Heart of the Creator (Savage)',
    name: 'Alexander - The Heart of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 587,
    rawName: 'Alexander - The Soul of the Creator (Savage)',
    name: 'Alexander - The Soul of the Creator',
    expansion: Expansion.Heavensward,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 593,
    rawName: 'the Palace of the Dead (Floors 51-60)',
    name: 'The Palace of the Dead (Floors 51-60)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 594,
    rawName: 'the Palace of the Dead (Floors 61-70)',
    name: 'The Palace of the Dead (Floors 61-70)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 595,
    rawName: 'the Palace of the Dead (Floors 71-80)',
    name: 'The Palace of the Dead (Floors 71-80)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 596,
    rawName: 'the Palace of the Dead (Floors 81-90)',
    name: 'The Palace of the Dead (Floors 81-90)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 597,
    rawName: 'the Palace of the Dead (Floors 91-100)',
    name: 'The Palace of the Dead (Floors 91-100)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 598,
    rawName: 'the Palace of the Dead (Floors 101-110)',
    name: 'The Palace of the Dead (Floors 101-110)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 599,
    rawName: 'the Palace of the Dead (Floors 111-120)',
    name: 'The Palace of the Dead (Floors 111-120)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 600,
    rawName: 'the Palace of the Dead (Floors 121-130)',
    name: 'The Palace of the Dead (Floors 121-130)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 601,
    rawName: 'the Palace of the Dead (Floors 131-140)',
    name: 'The Palace of the Dead (Floors 131-140)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 602,
    rawName: 'the Palace of the Dead (Floors 141-150)',
    name: 'The Palace of the Dead (Floors 141-150)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 603,
    rawName: 'the Palace of the Dead (Floors 151-160)',
    name: 'The Palace of the Dead (Floors 151-160)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 604,
    rawName: 'the Palace of the Dead (Floors 161-170)',
    name: 'The Palace of the Dead (Floors 161-170)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 605,
    rawName: 'the Palace of the Dead (Floors 171-180)',
    name: 'The Palace of the Dead (Floors 171-180)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 606,
    rawName: 'the Palace of the Dead (Floors 181-190)',
    name: 'The Palace of the Dead (Floors 181-190)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 607,
    rawName: 'the Palace of the Dead (Floors 191-200)',
    name: 'The Palace of the Dead (Floors 191-200)',
    expansion: Expansion.Heavensward,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 616,
    rawName: 'Shisui of the Violet Tides',
    name: 'Shisui of the Violet Tides',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 617,
    rawName: 'Sohm Al (Hard)',
    name: 'Sohm Al',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 627,
    rawName: 'Dun Scaith',
    name: 'Dun Scaith',
    expansion: Expansion.Heavensward,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 637,
    rawName: 'Containment Bay Z1T9',
    name: 'Containment Bay Z1T9',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 638,
    rawName: 'Containment Bay Z1T9 (Extreme)',
    name: 'Containment Bay Z1T9',
    expansion: Expansion.Heavensward,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 662,
    rawName: 'Kugane Castle',
    name: 'Kugane Castle',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 663,
    rawName: 'the Temple of the Fist',
    name: 'The Temple of the Fist',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 674,
    rawName: 'the Pool of Tribute',
    name: 'The Pool of Tribute',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 677,
    rawName: 'the Pool of Tribute (Extreme)',
    name: 'The Pool of Tribute',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 679,
    rawName: 'the Royal Menagerie',
    name: 'The Royal Menagerie',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 691,
    rawName: 'Deltascape V1.0',
    name: 'Deltascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 692,
    rawName: 'Deltascape V2.0',
    name: 'Deltascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 693,
    rawName: 'Deltascape V3.0',
    name: 'Deltascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 694,
    rawName: 'Deltascape V4.0',
    name: 'Deltascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 695,
    rawName: 'Deltascape V1.0 (Savage)',
    name: 'Deltascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 696,
    rawName: 'Deltascape V2.0 (Savage)',
    name: 'Deltascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 697,
    rawName: 'Deltascape V3.0 (Savage)',
    name: 'Deltascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 698,
    rawName: 'Deltascape V4.0 (Savage)',
    name: 'Deltascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 712,
    rawName: 'the Lost Canals of Uznair',
    name: 'The Lost Canals of Uznair',
    expansion: Expansion.Stormblood,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 719,
    rawName: 'Emanation',
    name: 'Emanation',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 720,
    rawName: 'Emanation (Extreme)',
    name: 'Emanation',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 725,
    rawName: 'the Hidden Canals of Uznair',
    name: 'The Hidden Canals of Uznair',
    expansion: Expansion.Stormblood,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 729,
    rawName: 'Astragalos',
    name: 'Astragalos',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 730,
    rawName: "the Minstrel's Ballad: Shinryu's Domain",
    name: "The Minstrel's Ballad: Shinryu's Domain",
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 732,
    rawName: 'the Forbidden Land, Eureka Anemos',
    name: 'The Forbidden Land, Eureka Anemos',
    expansion: Expansion.Stormblood,
    type: ContentType['Field Operation'],
  },
  {
    id: 733,
    rawName: 'the Unending Coil of Bahamut (Ultimate)',
    name: 'The Unending Coil of Bahamut',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 734,
    rawName: 'the Royal City of Rabanastre',
    name: 'The Royal City of Rabanastre',
    expansion: Expansion.Stormblood,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 742,
    rawName: "Hells' Lid",
    name: "Hells' Lid",
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 743,
    rawName: 'the Fractal Continuum (Hard)',
    name: 'The Fractal Continuum',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 746,
    rawName: 'the Jade Stoa',
    name: 'The Jade Stoa',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 748,
    rawName: 'Sigmascape V1.0',
    name: 'Sigmascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 749,
    rawName: 'Sigmascape V2.0',
    name: 'Sigmascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 750,
    rawName: 'Sigmascape V3.0',
    name: 'Sigmascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 751,
    rawName: 'Sigmascape V4.0',
    name: 'Sigmascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 752,
    rawName: 'Sigmascape V1.0 (Savage)',
    name: 'Sigmascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 753,
    rawName: 'Sigmascape V2.0 (Savage)',
    name: 'Sigmascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 754,
    rawName: 'Sigmascape V3.0 (Savage)',
    name: 'Sigmascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 755,
    rawName: 'Sigmascape V4.0 (Savage)',
    name: 'Sigmascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 758,
    rawName: 'the Jade Stoa (Extreme)',
    name: 'The Jade Stoa',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 761,
    rawName: 'the Great Hunt',
    name: 'The Great Hunt',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 762,
    rawName: 'the Great Hunt (Extreme)',
    name: 'The Great Hunt',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 763,
    rawName: 'the Forbidden Land, Eureka Pagos',
    name: 'The Forbidden Land, Eureka Pagos',
    expansion: Expansion.Stormblood,
    type: ContentType['Field Operation'],
  },
  {
    id: 768,
    rawName: "the Swallow's Compass",
    name: "The Swallow's Compass",
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 776,
    rawName: 'the Ridorana Lighthouse',
    name: 'The Ridorana Lighthouse',
    expansion: Expansion.Stormblood,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 777,
    rawName: "the Weapon's Refrain (Ultimate)",
    name: "The Weapon's Refrain",
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 778,
    rawName: 'Castrum Fluminis',
    name: 'Castrum Fluminis',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 779,
    rawName: "the Minstrel's Ballad: Tsukuyomi's Pain",
    name: "The Minstrel's Ballad: Tsukuyomi's Pain",
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 788,
    rawName: "Saint Mocianne's Arboretum (Hard)",
    name: "Saint Mocianne's Arboretum",
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Hard,
  },
  {
    id: 791,
    rawName: 'Hidden Gorge',
    name: 'Hidden Gorge',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 794,
    rawName: 'the Shifting Altars of Uznair',
    name: 'The Shifting Altars of Uznair',
    expansion: Expansion.Stormblood,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 795,
    rawName: 'the Forbidden Land, Eureka Pyros',
    name: 'The Forbidden Land, Eureka Pyros',
    expansion: Expansion.Stormblood,
    type: ContentType['Field Operation'],
  },
  {
    id: 798,
    rawName: 'Alphascape V1.0',
    name: 'Alphascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 799,
    rawName: 'Alphascape V2.0',
    name: 'Alphascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 800,
    rawName: 'Alphascape V3.0',
    name: 'Alphascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 801,
    rawName: 'Alphascape V4.0',
    name: 'Alphascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 802,
    rawName: 'Alphascape V1.0 (Savage)',
    name: 'Alphascape V1.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 803,
    rawName: 'Alphascape V2.0 (Savage)',
    name: 'Alphascape V2.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 804,
    rawName: 'Alphascape V3.0 (Savage)',
    name: 'Alphascape V3.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 805,
    rawName: 'Alphascape V4.0 (Savage)',
    name: 'Alphascape V4.0',
    expansion: Expansion.Stormblood,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 806,
    rawName: 'Kugane Ohashi',
    name: 'Kugane Ohashi',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 810,
    rawName: "Hells' Kier",
    name: "Hells' Kier",
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 811,
    rawName: "Hells' Kier (Extreme)",
    name: "Hells' Kier",
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 821,
    rawName: 'Dohn Mheg',
    name: 'Dohn Mheg',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 822,
    rawName: 'Mt. Gulg',
    name: 'Mt. Gulg',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 823,
    rawName: 'the Qitana Ravel',
    name: 'The Qitana Ravel',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 824,
    rawName: 'the Wreath of Snakes',
    name: 'The Wreath of Snakes',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 825,
    rawName: 'the Wreath of Snakes (Extreme)',
    name: 'The Wreath of Snakes',
    expansion: Expansion.Stormblood,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 826,
    rawName: 'the Orbonne Monastery',
    name: 'The Orbonne Monastery',
    expansion: Expansion.Stormblood,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 827,
    rawName: 'the Forbidden Land, Eureka Hydatos',
    name: 'The Forbidden Land, Eureka Hydatos',
    expansion: Expansion.Stormblood,
    type: ContentType['Field Operation'],
  },
  {
    id: 836,
    rawName: "Malikah's Well",
    name: "Malikah's Well",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 837,
    rawName: 'Holminster Switch',
    name: 'Holminster Switch',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 838,
    rawName: 'Amaurot',
    name: 'Amaurot',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 840,
    rawName: 'the Twinning',
    name: 'The Twinning',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 841,
    rawName: 'Akadaemia Anyder',
    name: 'Akadaemia Anyder',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 845,
    rawName: 'the Dancing Plague',
    name: 'The Dancing Plague',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 846,
    rawName: 'the Crown of the Immaculate',
    name: 'The Crown of the Immaculate',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 847,
    rawName: 'the Dying Gasp',
    name: 'The Dying Gasp',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 848,
    rawName: 'the Crown of the Immaculate (Extreme)',
    name: 'The Crown of the Immaculate',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 849,
    rawName: "Eden's Gate: Resurrection",
    name: "Eden's Gate: Resurrection",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 850,
    rawName: "Eden's Gate: Descent",
    name: "Eden's Gate: Descent",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 851,
    rawName: "Eden's Gate: Inundation",
    name: "Eden's Gate: Inundation",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 852,
    rawName: "Eden's Gate: Sepulture",
    name: "Eden's Gate: Sepulture",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 853,
    rawName: "Eden's Gate: Resurrection (Savage)",
    name: "Eden's Gate: Resurrection",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 854,
    rawName: "Eden's Gate: Descent (Savage)",
    name: "Eden's Gate: Descent",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 855,
    rawName: "Eden's Gate: Inundation (Savage)",
    name: "Eden's Gate: Inundation",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 856,
    rawName: "Eden's Gate: Sepulture (Savage)",
    name: "Eden's Gate: Sepulture",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 858,
    rawName: 'the Dancing Plague (Extreme)',
    name: 'The Dancing Plague',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 879,
    rawName: 'The Dungeons of Lyhe Ghiah',
    name: 'The Dungeons of Lyhe Ghiah',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 882,
    rawName: 'the Copied Factory',
    name: 'The Copied Factory',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 884,
    rawName: 'the Grand Cosmos',
    name: 'The Grand Cosmos',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 885,
    rawName: "the Minstrel's Ballad: Hades's Elegy",
    name: "The Minstrel's Ballad: Hades's Elegy",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 887,
    rawName: 'the Epic of Alexander (Ultimate)',
    name: 'The Epic of Alexander',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 888,
    rawName: 'Onsal Hakair (Danshig Naadam)',
    name: 'Onsal Hakair (Danshig Naadam)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 897,
    rawName: 'Cinder Drift',
    name: 'Cinder Drift',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 898,
    rawName: 'Anamnesis Anyder',
    name: 'Anamnesis Anyder',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 902,
    rawName: "Eden's Verse: Fulmination",
    name: "Eden's Verse: Fulmination",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 903,
    rawName: "Eden's Verse: Furor",
    name: "Eden's Verse: Furor",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 904,
    rawName: "Eden's Verse: Iconoclasm",
    name: "Eden's Verse: Iconoclasm",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 905,
    rawName: "Eden's Verse: Refulgence",
    name: "Eden's Verse: Refulgence",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 906,
    rawName: "Eden's Verse: Fulmination (Savage)",
    name: "Eden's Verse: Fulmination",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 907,
    rawName: "Eden's Verse: Furor (Savage)",
    name: "Eden's Verse: Furor",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 908,
    rawName: "Eden's Verse: Iconoclasm (Savage)",
    name: "Eden's Verse: Iconoclasm",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 909,
    rawName: "Eden's Verse: Refulgence (Savage)",
    name: "Eden's Verse: Refulgence",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 912,
    rawName: 'Cinder Drift (Extreme)',
    name: 'Cinder Drift',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 913,
    rawName: 'Memoria Misera (Extreme)',
    name: 'Memoria Misera',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 916,
    rawName: "the Heroes' Gauntlet",
    name: "The Heroes' Gauntlet",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 917,
    rawName: "the Puppets' Bunker",
    name: "The Puppets' Bunker",
    expansion: Expansion.Shadowbringers,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 920,
    rawName: 'the Bozjan Southern Front',
    name: 'The Bozjan Southern Front',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Field Operation'],
  },
  {
    id: 922,
    rawName: 'the Seat of Sacrifice',
    name: 'The Seat of Sacrifice',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 923,
    rawName: 'the Seat of Sacrifice (Extreme)',
    name: 'The Seat of Sacrifice',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 924,
    rawName: 'the Shifting Oubliettes of Lyhe Ghiah',
    name: 'The Shifting Oubliettes of Lyhe Ghiah',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 933,
    rawName: "Matoya's Relict",
    name: "Matoya's Relict",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 934,
    rawName: 'Castrum Marinum',
    name: 'Castrum Marinum',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 935,
    rawName: 'Castrum Marinum (Extreme)',
    name: 'Castrum Marinum',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 936,
    rawName: 'Delubrum Reginae',
    name: 'Delubrum Reginae',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Field Operation'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 937,
    rawName: 'Delubrum Reginae (Savage)',
    name: 'Delubrum Reginae',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Field Operation'],
    difficulty: Difficulty.Savage,
  },
  {
    id: 938,
    rawName: "Paglth'an",
    name: "Paglth'an",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 942,
    rawName: "Eden's Promise: Umbra",
    name: "Eden's Promise: Umbra",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 943,
    rawName: "Eden's Promise: Litany",
    name: "Eden's Promise: Litany",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 944,
    rawName: "Eden's Promise: Anamorphosis",
    name: "Eden's Promise: Anamorphosis",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 945,
    rawName: "Eden's Promise: Eternity",
    name: "Eden's Promise: Eternity",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 946,
    rawName: "Eden's Promise: Umbra (Savage)",
    name: "Eden's Promise: Umbra",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 947,
    rawName: "Eden's Promise: Litany (Savage)",
    name: "Eden's Promise: Litany",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 948,
    rawName: "Eden's Promise: Anamorphosis (Savage)",
    name: "Eden's Promise: Anamorphosis",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 949,
    rawName: "Eden's Promise: Eternity (Savage)",
    name: "Eden's Promise: Eternity",
    expansion: Expansion.Shadowbringers,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 950,
    rawName: 'the Cloud Deck',
    name: 'The Cloud Deck',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 951,
    rawName: 'the Cloud Deck (Extreme)',
    name: 'The Cloud Deck',
    expansion: Expansion.Shadowbringers,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 952,
    rawName: 'the Tower of Zot',
    name: 'The Tower of Zot',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 966,
    rawName: "the Tower at Paradigm's Breach",
    name: "The Tower at Paradigm's Breach",
    expansion: Expansion.Shadowbringers,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 968,
    rawName: "Dragonsong's Reprise (Ultimate)",
    name: "Dragonsong's Reprise",
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 969,
    rawName: 'the Tower of Babil',
    name: 'The Tower of Babil',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 970,
    rawName: 'Vanaspati',
    name: 'Vanaspati',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 973,
    rawName: 'the Dead Ends',
    name: 'The Dead Ends',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 974,
    rawName: 'Ktisis Hyperboreia',
    name: 'Ktisis Hyperboreia',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 975,
    rawName: 'Zadnor',
    name: 'Zadnor',
    expansion: Expansion.Shadowbringers,
    type: ContentType['Field Operation'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 976,
    rawName: 'Smileton',
    name: 'Smileton',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 978,
    rawName: 'the Aitiascope',
    name: 'The Aitiascope',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 986,
    rawName: 'the Stigma Dreamscape',
    name: 'The Stigma Dreamscape',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 992,
    rawName: 'the Dark Inside',
    name: 'The Dark Inside',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 993,
    rawName: "the Minstrel's Ballad: Zodiark's Fall",
    name: "The Minstrel's Ballad: Zodiark's Fall",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 995,
    rawName: 'the Mothercrystal',
    name: 'The Mothercrystal',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 996,
    rawName: "the Minstrel's Ballad: Hydaelyn's Call",
    name: "The Minstrel's Ballad: Hydaelyn's Call",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 997,
    rawName: 'the Final Day',
    name: 'The Final Day',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 998,
    rawName: "the Minstrel's Ballad: Endsinger's Aria",
    name: "The Minstrel's Ballad: Endsinger's Aria",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1000,
    rawName: 'the Excitatron 6000',
    name: 'The Excitatron 6000',
    expansion: Expansion.Endwalker,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 1002,
    rawName: 'Asphodelos: The First Circle',
    name: 'Asphodelos: The First Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1003,
    rawName: 'Asphodelos: The First Circle (Savage)',
    name: 'Asphodelos: The First Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1004,
    rawName: 'Asphodelos: The Second Circle',
    name: 'Asphodelos: The Second Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1005,
    rawName: 'Asphodelos: The Second Circle (Savage)',
    name: 'Asphodelos: The Second Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1006,
    rawName: 'Asphodelos: The Third Circle',
    name: 'Asphodelos: The Third Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1007,
    rawName: 'Asphodelos: The Third Circle (Savage)',
    name: 'Asphodelos: The Third Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1008,
    rawName: 'Asphodelos: The Fourth Circle',
    name: 'Asphodelos: The Fourth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1009,
    rawName: 'Asphodelos: The Fourth Circle (Savage)',
    name: 'Asphodelos: The Fourth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1036,
    rawName: 'Sastasha',
    name: 'Sastasha',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1037,
    rawName: 'the Tam–Tara Deepcroft',
    name: 'The Tam–Tara Deepcroft',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1038,
    rawName: 'Copperbell Mines',
    name: 'Copperbell Mines',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1039,
    rawName: 'the Thousand Maws of Toto–Rak',
    name: 'The Thousand Maws of Toto–Rak',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1040,
    rawName: 'Haukke Manor',
    name: 'Haukke Manor',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1041,
    rawName: "Brayflox's Longstop",
    name: "Brayflox's Longstop",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1042,
    rawName: 'the Stone Vigil',
    name: 'The Stone Vigil',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1043,
    rawName: 'Castrum Meridianum',
    name: 'Castrum Meridianum',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1044,
    rawName: 'the Praetorium',
    name: 'The Praetorium',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1045,
    rawName: 'the Bowl of Embers',
    name: 'The Bowl of Embers',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1046,
    rawName: 'the Navel',
    name: 'The Navel',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1047,
    rawName: 'the Howling Eye',
    name: 'The Howling Eye',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1048,
    rawName: 'the Porta Decumana',
    name: 'The Porta Decumana',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1050,
    rawName: "Alzadaal's Legacy",
    name: "Alzadaal's Legacy",
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1054,
    rawName: 'Aglaia',
    name: 'Aglaia',
    expansion: Expansion.Endwalker,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1062,
    rawName: 'Snowcloak',
    name: 'Snowcloak',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1063,
    rawName: 'the Keeper of the Lake',
    name: 'The Keeper of the Lake',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1064,
    rawName: 'Sohm Al',
    name: 'Sohm Al',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1065,
    rawName: 'the Aery',
    name: 'The Aery',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1066,
    rawName: 'the Vault',
    name: 'The Vault',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1067,
    rawName: 'Thornmarch (Hard)',
    name: 'Thornmarch',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Trial,
    difficulty: Difficulty.Hard,
  },
  {
    id: 1069,
    rawName: "the Sil'dihn Subterrane",
    name: "The Sil'dihn Subterrane",
    expansion: Expansion.Endwalker,
    type: ContentType['Variant Dungeon'],
  },
  {
    id: 1070,
    rawName: 'the Fell Court of Troia',
    name: 'The Fell Court of Troia',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1071,
    rawName: "Storm's Crown",
    name: "Storm's Crown",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1072,
    rawName: "Storm's Crown (Extreme)",
    name: "Storm's Crown",
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1075,
    rawName: "Another Sil'dihn Subterrane",
    name: "Another Sil'dihn Subterrane",
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1076,
    rawName: "Another Sil'dihn Subterrane (Savage)",
    name: "Another Sil'dihn Subterrane",
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Savage,
  },
  {
    id: 1081,
    rawName: 'Abyssos: The Fifth Circle',
    name: 'Abyssos: The Fifth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1082,
    rawName: 'Abyssos: The Fifth Circle (Savage)',
    name: 'Abyssos: The Fifth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1083,
    rawName: 'Abyssos: The Sixth Circle',
    name: 'Abyssos: The Sixth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1084,
    rawName: 'Abyssos: The Sixth Circle (Savage)',
    name: 'Abyssos: The Sixth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1085,
    rawName: 'Abyssos: The Seventh Circle',
    name: 'Abyssos: The Seventh Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1086,
    rawName: 'Abyssos: The Seventh Circle (Savage)',
    name: 'Abyssos: The Seventh Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1087,
    rawName: 'Abyssos: The Eighth Circle',
    name: 'Abyssos: The Eighth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1088,
    rawName: 'Abyssos: The Eighth Circle (Savage)',
    name: 'Abyssos: The Eighth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1095,
    rawName: 'Mount Ordeals',
    name: 'Mount Ordeals',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1096,
    rawName: 'Mount Ordeals (Extreme)',
    name: 'Mount Ordeals',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1097,
    rawName: 'Lapis Manalis',
    name: 'Lapis Manalis',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1099,
    rawName: 'Eureka Orthos (Floors 1-10)',
    name: 'Eureka Orthos (Floors 1-10)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1100,
    rawName: 'Eureka Orthos (Floors 11-20)',
    name: 'Eureka Orthos (Floors 11-20)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1101,
    rawName: 'Eureka Orthos (Floors 21-30)',
    name: 'Eureka Orthos (Floors 21-30)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1102,
    rawName: 'Eureka Orthos (Floors 31-40)',
    name: 'Eureka Orthos (Floors 31-40)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1103,
    rawName: 'Eureka Orthos (Floors 41-50)',
    name: 'Eureka Orthos (Floors 41-50)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1104,
    rawName: 'Eureka Orthos (Floors 51-60)',
    name: 'Eureka Orthos (Floors 51-60)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1105,
    rawName: 'Eureka Orthos (Floors 61-70)',
    name: 'Eureka Orthos (Floors 61-70)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1106,
    rawName: 'Eureka Orthos (Floors 71-80)',
    name: 'Eureka Orthos (Floors 71-80)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1107,
    rawName: 'Eureka Orthos (Floors 81-90)',
    name: 'Eureka Orthos (Floors 81-90)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1108,
    rawName: 'Eureka Orthos (Floors 91-100)',
    name: 'Eureka Orthos (Floors 91-100)',
    expansion: Expansion.Endwalker,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1109,
    rawName: 'the Great Gubal Library',
    name: 'The Great Gubal Library',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1110,
    rawName: 'the Aetherochemical Research Facility',
    name: 'The Aetherochemical Research Facility',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1111,
    rawName: 'the Antitower',
    name: 'The Antitower',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1112,
    rawName: 'Sohr Khai',
    name: 'Sohr Khai',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1113,
    rawName: 'Xelphatol',
    name: 'Xelphatol',
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1114,
    rawName: "Baelsar's Wall",
    name: "Baelsar's Wall",
    expansion: Expansion.Heavensward,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1118,
    rawName: 'Euphrosyne',
    name: 'Euphrosyne',
    expansion: Expansion.Endwalker,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1122,
    rawName: 'the Omega Protocol (Ultimate)',
    name: 'The Omega Protocol',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 1123,
    rawName: 'the Shifting Gymnasion Agonon',
    name: 'The Shifting Gymnasion Agonon',
    expansion: Expansion.Endwalker,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 1126,
    rawName: 'the Aetherfont',
    name: 'The Aetherfont',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1136,
    rawName: 'the Gilded Araya',
    name: 'The Gilded Araya',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1137,
    rawName: 'Mount Rokkon',
    name: 'Mount Rokkon',
    expansion: Expansion.Endwalker,
    type: ContentType['Variant Dungeon'],
  },
  {
    id: 1140,
    rawName: 'the Voidcast Dais',
    name: 'The Voidcast Dais',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1141,
    rawName: 'the Voidcast Dais (Extreme)',
    name: 'The Voidcast Dais',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1142,
    rawName: 'the Sirensong Sea',
    name: 'The Sirensong Sea',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1143,
    rawName: "Bardam's Mettle",
    name: "Bardam's Mettle",
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1144,
    rawName: 'Doma Castle',
    name: 'Doma Castle',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1145,
    rawName: 'Castrum Abania',
    name: 'Castrum Abania',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1146,
    rawName: 'Ala Mhigo',
    name: 'Ala Mhigo',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1147,
    rawName: 'Anabaseios: The Ninth Circle',
    name: 'Anabaseios: The Ninth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1148,
    rawName: 'Anabaseios: The Ninth Circle (Savage)',
    name: 'Anabaseios: The Ninth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1149,
    rawName: 'Anabaseios: The Tenth Circle',
    name: 'Anabaseios: The Tenth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1150,
    rawName: 'Anabaseios: The Tenth Circle (Savage)',
    name: 'Anabaseios: The Tenth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1151,
    rawName: 'Anabaseios: The Eleventh Circle',
    name: 'Anabaseios: The Eleventh Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1152,
    rawName: 'Anabaseios: The Eleventh Circle (Savage)',
    name: 'Anabaseios: The Eleventh Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1153,
    rawName: 'Anabaseios: The Twelfth Circle',
    name: 'Anabaseios: The Twelfth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1154,
    rawName: 'Anabaseios: The Twelfth Circle (Savage)',
    name: 'Anabaseios: The Twelfth Circle',
    expansion: Expansion.Endwalker,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1155,
    rawName: 'Another Mount Rokkon',
    name: 'Another Mount Rokkon',
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1156,
    rawName: 'Another Mount Rokkon (Savage)',
    name: 'Another Mount Rokkon',
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Savage,
  },
  {
    id: 1164,
    rawName: 'the Lunar Subterrane',
    name: 'The Lunar Subterrane',
    expansion: Expansion.Endwalker,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1167,
    rawName: 'Ihuykatumu',
    name: 'Ihuykatumu',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1168,
    rawName: 'the Abyssal Fracture',
    name: 'The Abyssal Fracture',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1169,
    rawName: 'the Abyssal Fracture (Extreme)',
    name: 'The Abyssal Fracture',
    expansion: Expansion.Endwalker,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1172,
    rawName: 'the Drowned City of Skalla',
    name: 'The Drowned City of Skalla',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1173,
    rawName: 'the Burn',
    name: 'The Burn',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1174,
    rawName: 'the Ghimlyt Dark',
    name: 'The Ghimlyt Dark',
    expansion: Expansion.Stormblood,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1176,
    rawName: 'Aloalo Island',
    name: 'Aloalo Island',
    expansion: Expansion.Endwalker,
    type: ContentType['Variant Dungeon'],
  },
  {
    id: 1178,
    rawName: 'Thaleia',
    name: 'Thaleia',
    expansion: Expansion.Endwalker,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1179,
    rawName: 'Another Aloalo Island',
    name: 'Another Aloalo Island',
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1180,
    rawName: 'Another Aloalo Island (Savage)',
    name: 'Another Aloalo Island',
    expansion: Expansion.Endwalker,
    type: ContentType['Criterion Dungeon'],
    difficulty: Difficulty.Savage,
  },
  {
    id: 1193,
    rawName: 'Worqor Zormor',
    name: 'Worqor Zormor',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1194,
    rawName: 'the Skydeep Cenote',
    name: 'The Skydeep Cenote',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1195,
    rawName: 'Worqor Lar Dor',
    name: 'Worqor Lar Dor',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1196,
    rawName: 'Worqor Lar Dor (Extreme)',
    name: 'Worqor Lar Dor',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1198,
    rawName: 'Vanguard',
    name: 'Vanguard',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1199,
    rawName: 'Alexandria',
    name: 'Alexandria',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1200,
    rawName: 'Everkeep',
    name: 'Everkeep',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1201,
    rawName: 'Everkeep (Extreme)',
    name: 'Everkeep',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1202,
    rawName: 'the Interphos',
    name: 'The Interphos',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1203,
    rawName: 'Tender Valley',
    name: 'Tender Valley',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1204,
    rawName: 'The Strayborough Deadwalk',
    name: 'The Strayborough Deadwalk',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1208,
    rawName: 'Origenics',
    name: 'Origenics',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1209,
    rawName: 'Cenote Ja Ja Gural',
    name: 'Cenote Ja Ja Gural',
    expansion: Expansion.Dawntrail,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 1225,
    rawName: 'AAC Light-heavyweight M1',
    name: 'AAC Light-heavyweight M1',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1226,
    rawName: 'AAC Light-heavyweight M1 (Savage)',
    name: 'AAC Light-heavyweight M1',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1227,
    rawName: 'AAC Light-heavyweight M2',
    name: 'AAC Light-heavyweight M2',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1228,
    rawName: 'AAC Light-heavyweight M2 (Savage)',
    name: 'AAC Light-heavyweight M2',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1229,
    rawName: 'AAC Light-heavyweight M3',
    name: 'AAC Light-heavyweight M3',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1230,
    rawName: 'AAC Light-heavyweight M3 (Savage)',
    name: 'AAC Light-heavyweight M3',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1231,
    rawName: 'AAC Light-heavyweight M4',
    name: 'AAC Light-heavyweight M4',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1232,
    rawName: 'AAC Light-heavyweight M4 (Savage)',
    name: 'AAC Light-heavyweight M4',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1238,
    rawName: 'Futures Rewritten (Ultimate)',
    name: 'Futures Rewritten',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Ultimate,
  },
  {
    id: 1241,
    rawName: 'The Cloud of Darkness (Chaotic)',
    name: 'The Cloud of Darkness',
    expansion: Expansion.Dawntrail,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Chaotic,
  },
  {
    id: 1242,
    rawName: 'Yuweyawata Field Station',
    name: 'Yuweyawata Field Station',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1243,
    rawName: "the Minstrel's Ballad: Sphene's Burden",
    name: "The Minstrel's Ballad: Sphene's Burden",
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1245,
    rawName: 'Halatali',
    name: 'Halatali',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1248,
    rawName: 'Jeuno: The First Walk',
    name: 'Jeuno: The First Walk',
    expansion: Expansion.Dawntrail,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1252,
    rawName: 'the Occult Crescent: South Horn',
    name: 'The Occult Crescent: South Horn',
    expansion: Expansion.Dawntrail,
    type: ContentType['Field Operation'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1256,
    rawName: 'AAC Cruiserweight M1',
    name: 'AAC Cruiserweight M1',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1257,
    rawName: 'AAC Cruiserweight M1 (Savage)',
    name: 'AAC Cruiserweight M1',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1258,
    rawName: 'AAC Cruiserweight M2',
    name: 'AAC Cruiserweight M2',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1259,
    rawName: 'AAC Cruiserweight M2 (Savage)',
    name: 'AAC Cruiserweight M2',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1260,
    rawName: 'AAC Cruiserweight M3',
    name: 'AAC Cruiserweight M3',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1261,
    rawName: 'AAC Cruiserweight M3 (Savage)',
    name: 'AAC Cruiserweight M3',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1262,
    rawName: 'AAC Cruiserweight M4',
    name: 'AAC Cruiserweight M4',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1263,
    rawName: 'AAC Cruiserweight M4 (Savage)',
    name: 'AAC Cruiserweight M4',
    expansion: Expansion.Dawntrail,
    type: ContentType.Raid,
    difficulty: Difficulty.Savage,
  },
  {
    id: 1266,
    rawName: 'the Underkeep',
    name: 'The Underkeep',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1267,
    rawName: 'the Sunken Temple of Qarn',
    name: 'The Sunken Temple of Qarn',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1270,
    rawName: 'Recollection',
    name: 'Recollection',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1271,
    rawName: 'Recollection (Extreme)',
    name: 'Recollection',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1273,
    rawName: 'the Borderland Ruins (Secure)',
    name: 'The Borderland Ruins (Secure)',
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.PVP,
  },
  {
    id: 1279,
    rawName: 'Vault Oneiron',
    name: 'Vault Oneiron',
    expansion: Expansion.Dawntrail,
    type: ContentType['Treasure Dungeon'],
  },
  {
    id: 1281,
    rawName: "Pilgrim's Traverse (Stones 1-10)",
    name: "Pilgrim's Traverse (Stones 1-10)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1282,
    rawName: "Pilgrim's Traverse (Stones 11-20)",
    name: "Pilgrim's Traverse (Stones 11-20)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1283,
    rawName: "Pilgrim's Traverse (Stones 21-30)",
    name: "Pilgrim's Traverse (Stones 21-30)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1284,
    rawName: "Pilgrim's Traverse (Stones 31-40)",
    name: "Pilgrim's Traverse (Stones 31-40)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1285,
    rawName: "Pilgrim's Traverse (Stones 41-50)",
    name: "Pilgrim's Traverse (Stones 41-50)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1286,
    rawName: "Pilgrim's Traverse (Stones 51-60)",
    name: "Pilgrim's Traverse (Stones 51-60)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1287,
    rawName: "Pilgrim's Traverse (Stones 61-70)",
    name: "Pilgrim's Traverse (Stones 61-70)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1288,
    rawName: "Pilgrim's Traverse (Stones 71-80)",
    name: "Pilgrim's Traverse (Stones 71-80)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1289,
    rawName: "Pilgrim's Traverse (Stones 81-90)",
    name: "Pilgrim's Traverse (Stones 81-90)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1290,
    rawName: "Pilgrim's Traverse (Stones 91-100)",
    name: "Pilgrim's Traverse (Stones 91-100)",
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1292,
    rawName: 'the Meso Terminal',
    name: 'The Meso Terminal',
    expansion: Expansion.Dawntrail,
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1295,
    rawName: 'the Ageless Necropolis',
    name: 'The Ageless Necropolis',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1296,
    rawName: "the Minstrel's Ballad: Necron's Embrace",
    name: "The Minstrel's Ballad: Necron's Embrace",
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1300,
    rawName: 'the Windward Wilds',
    name: 'The Windward Wilds',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1302,
    rawName: 'the Wreath of Snakes (Unreal)',
    name: 'The Wreath of Snakes',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Unreal,
  },
  {
    id: 1303,
    rawName: "Cutter's Cry",
    name: "Cutter's Cry",
    expansion: Expansion['A Realm Reborn'],
    type: ContentType.Dungeon,
    difficulty: Difficulty.Normal,
  },
  {
    id: 1304,
    rawName: "San d'Oria: The Second Walk",
    name: "San d'Oria: The Second Walk",
    expansion: Expansion.Dawntrail,
    type: ContentType['Alliance Raid'],
    difficulty: Difficulty.Normal,
  },
  {
    id: 1306,
    rawName: 'the Windward Wilds (Extreme)',
    name: 'The Windward Wilds',
    expansion: Expansion.Dawntrail,
    type: ContentType.Trial,
    difficulty: Difficulty.Extreme,
  },
  {
    id: 1311,
    rawName: 'the Final Verse (Quantum)',
    name: 'The Final Verse',
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Quantum,
  },
  {
    id: 1333,
    rawName: 'the Final Verse',
    name: 'The Final Verse',
    expansion: Expansion.Dawntrail,
    type: ContentType['Deep Dungeon'],
    difficulty: Difficulty.Normal,
  },
];

const bosses = new Map<number, string>([
  // 1204: 'Chopper',
  // 'Captain Madison',
  // 1206: 'Denn the Orcatoothed',
  // [455, 'Void Soulcounter'],
  // [73, 'Galvanth the Dominator'],
  // [548, 'Kottos'],
  // 'Ichorous Ire',
  // 'Gyges the Great',
  // 'Firemane',
  // 'Thunderclap Guivre',
  // 'Pit Peiste',
  // "Coeurl O' Nine Tails",
  // 'Graffias',
  // 'Manor Claviger',
  // 'Manor Jester',
  // 'Lady Amandine',
  // 'Great Yellow Pelican',
  // 'Inferno Drake',
  // 'Hellbender',
  // 'Deep Jungle Coeurl',
  // 'Aiatar',
  // 'Teratotaur',
  // 'Temple Guardian',
  // 'Adjudicator',
  // 'Myrmidon Princess',
  // 'Giant Tunnel Worm',
  // 'Chimera',
  // 'Chudo-Yudo',
  // 'Koshchei',
  // 'Isgebind',
  // 'All-seeing Eye',
  // 'Taulurd',
  // 'Batraal',
  [1534, 'Locksmith'],
  [1533, 'Coincounter'],
  [1532, "Miser's Mistress"],
  // 'The Black Eft',
  // 'Magitek Vanguard F-1',
  // 'Livia sas Junius',
  // 'Mark II Magitek Colossus',
  // 'Nero tol Scaeva',
  // 'Gaius van Baelsar',
  // 'Keeper of Halidom',
  // 'Giant Bavarois',
  // 'Tonberry King',
  // 'Lunatic Priest',
  // 'Demon Wall',
  // 'Anantaboga',
  // 'Symond the Unsinkable',
  // 'Zu',
  // 'Tyrant',
  // 'Siren',
  // 'Hecatoncheir Mastermind',
  // 'Gogmagolem',
  // 'Ouranos',
  // 'Manor Jester',
  // 'Ash',
  // 'Halicarnassus',
  // 'Decaying Gourmand',
  // 'Arioch',
  // 'Diabolos',
  // 'Pyracmon',
  // 'Catoblepas',
  // 'Narasimha',
  // 'Illuminati Commander',
  // 'Magitek Vangob G-III',
  // 'Gobmachine G-VI',
  // 'Sasquatch',
  // 'Sjoorm',
  // 'Kraken',
  // 'Liavinne',
  // 'Spare Body',
  // 'Avere Bravearm',
  // 'Gorynich',
  // 'Cuca Fera',
  // 'Giruveganaus',
  // 'Wandil',
  // 'Yeti',
  // 'Fenrir',
  // 'Karlabos',
  // 'Captain Madison',
  // 'Kraken',
  // 'Damaged Adjudicator',
  // 'Sabotender Emperatriz',
  // 'Vicegerent to the Warden',
  // 'Einhander',
  // 'Magitek Gunship',
  // 'Midgardsormr',
  // 'Frumious Koheel Ja',
  // 'Slithy Zolool Ja',
  // 'Manxome Molaa Ja Ja',
  // 'Anchag',
  // 'Boodyman',
  // 'Ferdiad',
  // 'Towering Oliphant',
  // 'Ser Yuhelmeric',
  // 'Opinicus',
  // 'Raskovnik',
  // 'Myath',
  // 'Tioman',
  // 'Rangda',
  // 'Gyascutus',
  // 'Nidhogg',
  // 'Ser Adelphel Brightblade',
  // 'Ser Grinnaux The Bull',
  // 'Ser Charibert',
  // 'Demon Tome',
  // 'Byblos',
  // 'The Everliving Bibliotaph',
  // 'Regula van Hydrus',
  // 'Harmachis',
  // 'Lahabrea',
  // 'Ascian Prime',
  // 'Nunyenunc',
  // 'Canu Vanu',
  // 'Waukkeon',
  // 'Phantom Ray',
  // 'Minotaur',
  // 'The Curator',
  // 'Rose Garden',
  // 'Queen Hawk',
  // 'Belladonna',
  // 'Ghrah Luminary',
  // '8th Order Patriarch Be Gu',
  // 'Progenitrix',
  // 'Zuro Roggo',
  // 'Ziggy',
  // 'Calcabrina',
  // 'Achamoth',
  // 'Winged Lion',
  // 'Kuribu',
  // 'Chieftain Moglin',
  // 'Poqhiraj',
  // 'Hraesvelgr',
  // 'Battle Coeurl',
  // 'Ymir',
  // 'Mistbeard',
  // 'Nuzal Hueloc',
  // 'Dotoli Ciloc',
  // 'Tozol Huatotl',
  // 'Demon of the Tome',
  // 'Liquid Flame',
  // 'Strix',
  // 'Magitek Predator',
  // 'Armored Weapon',
  // 'The Griffin',
  // 'The Leightonward',
  // 'Gowrow',
  // 'Lava Scorpion',
  // 'Lugat',
  // 'The Governor',
  // 'Lorelei',
  // 'Amikiri',
  // 'Ruby Princess',
  // 'Shisui Yohi',
  // 'Garula',
  // 'Bardam',
  // 'Yol',
  // 'Magitek Rearguard',
  // 'Magitek Hexadrone',
  // 'Hypertuned Grynewaht',
  // 'Magna Roader',
  // 'Subject Number XXIV',
  // 'Inferno',
  // 'Magitek Scorpion',
  // 'Aulus mal Asina',
  // 'Zenos yae Galvus',
  // 'Zuiko-maru',
  // 'Dojun-maru',
  // 'Yojimbo',
  // 'Coeurl Sruti',
  // 'Arbuda',
  // 'Ivon Coeurlfist',
  // 'Kelpie',
  // 'The Old One',
  // 'Hrodric Poisontongue',
  // 'Otake-maru',
  // 'Kamaitachi',
  // 'Genbu',
  // 'Motherbit',
  // 'The Ultima Warrior',
  // 'The Ultima Beast',
  // 'Otengu',
  // 'Daidarabotchi',
  // 'Qitian Dasheng',
  // 'Hedetet',
  // 'Defective Drone',
  // 'Mist Dragon',
  // 'Nullchu',
  // 'Lakhamu',
  // 'Tokkapchi',
  // 'Mark III-B Magitek Colossus',
  // 'Prometheus',
  // 'Annia quo Soranus',
  // 'Forgiven Dissonance',
  // 'Tesleen, the Forgiven',
  // 'Lightwarden Philia',
  // 'Aenc Thon, Lord of the Lingering Gaze',
  // 'Griaule',
  // 'Lakelord: Aenc Thon, Lord of the Lengthsome Gait',
  // 'Lozatl',
  // 'Batsquatch',
  // 'Lightwarden: Eros',
  // 'Greater Armadillo',
  // 'Amphibious Talos',
  // 'Lightwarden: Storge',
  // 'Forgiven Cruelty',
  // 'Forgiven Whimsy',
  // 'Consrot of Sin: Forgiven Obscenity',
  // 'The First Beast',
  // 'Terminus Bellwether',
  // 'Chthonic Riddle: Therion',
  // 'Alpha Zaghnal',
  // 'Mithridates',
  // 'Artificial Enigma: The Tycoon',
  // 'Cladoselache',
  // 'Marquis Morbol',
  // 'Guardian Force: Quetzalcoatl',
  // 'Seeker of Solitude',
  // 'Leannan Sith',
  // 'Insatiable Flame: Lugus',
  // 'Unknown',
  // 'Kyklops',
  // 'Merciless Matriarch: Rukshs Dheem',
  // 'Spectral Thief',
  // 'Spectral Necromancer',
  // 'Distant Ideal: Spectral Berserker',
  // 'Mudman',
  // 'Nixie',
  // 'Porcine Porcelain: Mother Porxie',
  // 'Amhuluk',
  // 'Magitek Fortress',
  // 'Telotherium: Lunar Bahamut',
  // 'Minduruva',
  // 'Sanduruva',
  // 'Harbingers Elect: Cinduruva',
  // 'Barnabas',
  // 'Lugae',
  // 'Eikon of Eikons: Anima',
  // 'Terminus Snatcher',
  // 'Terminus Wrecker',
  // 'Blasphemy: Svarbhanu',
  // 'Lyssa',
  // 'Ladon Lord',
  // 'Winged Defiance: Hermes',
  // 'Livia the Undeterred',
  // 'Rhitahtyn the Unshakable',
  // 'Sundered Soul: Amon the Undying',
  // 'Caustic Grebuloff',
  // 'Peacekeeper',
  // 'The Last Mercy: Ra-la',
  // 'Face',
  // 'Frameworker',
  // 'Smilemaker: The Big Cheese',
  // 'Proto-Omega',
  // 'Arch-Lambda',
  // 'Siege Matrix: Stigma-4',
  // 'Ambujam',
  // 'Armored Chariot',
  // 'Looming Warden: Kapikulu',
  // 'Evil Dreamers',
  // 'Beatrice',
  // 'Blighted Despot: Scarmiglione',
  // 'Albion',
  // 'Galatea Magna',
  // 'Drowned King: Cagnazzo',
  // 'Lyngbakr',
  // 'Arkas',
  // 'Slumbering Scourge: Octomammoth',
  // 'Dark Elf',
  // 'Damcyan Antlion',
  // 'Memoriate: Durante',
  // 'Prime Punutiy',
  // 'Drowsie',
  // 'Apex Predator: Apollyon',
  // 'Ryoqor Terteh',
  // 'Kahderyor',
  // "Dawn's Elector: Gurfurlur",
  // 'Feather Ray',
  // 'Firearms',
  // 'Sculptor of Silence: Maulskull',
  // 'Vanguard Commander R8',
  // 'Protector',
  // 'Ophidian Outrider: Zander the Snakeskinner',
  // 'Herpekaris',
  // 'Deceiver',
  // "Innovation's Excess: Ambrose the Undeparted",
  // 'Antivirus X',
  // 'Amalgam',
  // 'Bleeding-edge Technology: Elimator',
  // 'Barreltender',
  // 'Anthracite',
  // 'Inexplicable Entity: The Greatest Serpent of Tural',
  // 'His Royal Headness Leonogg I',
  // 'Jack-in-the-Pot',
  // 'Daylit Nightmare: Träumerei',
  // 'Lindblum Zaghnal',
  // 'Overseer Kanilokka',
  // 'Tural Vidraal: Lunipyati',
  // 'Gargant',
  // 'Soldier 50',
  // 'Indefatigable Defense: Valia Pira',
  // 'Chirurgeon General',
  // 'Hooded Headsmen',
  // 'Memory Meld: The Immortal Remains',
]);

export { zones, bosses };
